### PR TITLE
added checkstyle plugin

### PR DESCRIPTION
**Pull request by krichter722**

### CODE REVIEW

**Comment by krichter722** [comment]
Please restart Travis (see #6 for reason).

**Comment by BalusC** [comment]
Sorry, no changes to code style please.

**Comment by krichter722** [comment]
Are you interested in the checkstyle setup without the removal of tab characters (don't see the reason why to keep them, but I accept your decision)?

**Comment by BalusC** [comment]
Sorry, not interested in checkstyle. If you care about source code formatting just use IDE builtin autoformatting or integrate e.g. Jalopy in build.

**Pull request closed without merging**
